ZFB_TRADE_DETAIL_KEYS:
  # 通用
  - '订单金额'
  - '红包'
  - '付款方式'
  - '商品说明'
  - '创建时间'
  - '订单号'
  - '商家订单号'

  - '收货地址'
  - '物流信息'

  - '缴费说明'
  - '户号'

  - '对方账户'

  - '转账说明'

  # 底部其他，如果出现：更多、账单分类、标签和备注，直接结束

WX_TRADE_DETAIL_KEYS:
  # 退款
  - '退款记录'

  # 通用
  - '原价'
  - '优惠'
  - '当前状态'
  - '商品'
  - '商户全称'
  - '支付时间'
  - '支付方式'
  - '交易单号'
  - '商户单号'

  # 转账
  - '转账说明'
  - '转账时间'
  - '收款时间'
  - '转账单号'

  # 红包
  - '红包详情'